### ISSUE TITLE
Crash When Generating New A Chunk [IllegalArgumentException]

### ISSUE THREAD

**Issue by r-mc2** [NillerMedDild/Enigmatica6#1029]
**Modpack version**
v0.3.6

**Describe the bug**
Was out looking for an Origin Biome from BoP and found it fine, but decided to check out the surrounding area as it looked like a Mooshroom biome nearby. Got close to some chunk that as it was generating seemed to make Minecraft think to check if a block of Air was "lit" like a Redstone Ore block. Air doesn't have a "lit" state so server threw an IllegalArgumentException.

I'm not fully certain where the issue lies but Quark, Emendataus Enigmatica, & FerriteCore were all called out in the stacktrace. Something to do with a mixin checking a TNT minecart entity then further up the stacktrace looking at Emendatus' redstone ore, then immediately FerriteCore doing something with its NoPropertyStateHolderMixin.

Logging back in after the server came back up threw the exception again, but editing my player NBT file and changing the current position back to somewhere I had already generated safely has worked around it for now. I may even try deleting that region file or chunk (if I can figure out how to remove a single chunk from a region file) and see if it regens more cleanly, but I'll wait to see if there is better advice on this.

**Logs**
<details>
<summary>Click to show/hide stacktrace</summary>
<p>
<pre>
Description: Ticking entity

java.lang.IllegalArgumentException: Cannot get property BooleanProperty{name=lit, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in Block{minecraft:air}
	at net.minecraft.state.StateHolder.func_177229_b(SourceFile:95) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:ferritecore:Replace StateHolder::getValues in StateHolder::toString,pl:mixin:APP:ferritecore.fastmap.mixin.json:FastMapStateHolderMixin,pl:mixin:APP:ferritecore.nopropertymap.mixin.json:NoPropertyStateHolderMixin,pl:mixin:A}
	at com.ridanisaurus.emendatusenigmatica.blocks.OreRedstone.activate(OreRedstone.java:109) ~[emendatusenigmatica:1.1] {re:classloading,pl:runtimedistcleaner:A}
	at com.ridanisaurus.emendatusenigmatica.blocks.OreRedstone.func_176199_a(OreRedstone.java:91) ~[emendatusenigmatica:1.1] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.entity.Entity.func_213315_a(Entity.java:564) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:astralsorcery:add_custom_entity_collision,pl:mixin:APP:randompatches.mixins.json:EntityMixin,pl:mixin:APP:structure_gel.mixins.json:EntityMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.EntityAccess,pl:mixin:APP:quark.mixins.json:EntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.entity.item.minecart.AbstractMinecartEntity.func_180459_n(AbstractMinecartEntity.java:393) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:quark.mixins.json:AbstractMinecartEntityMixin,pl:mixin:APP:assets/botania/botania.mixins.json:MixinAbstractMinecartEntity,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.entity.item.minecart.AbstractMinecartEntity.func_70071_h_(AbstractMinecartEntity.java:317) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:quark.mixins.json:AbstractMinecartEntityMixin,pl:mixin:APP:assets/botania/botania.mixins.json:MixinAbstractMinecartEntity,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.entity.item.minecart.TNTMinecartEntity.func_70071_h_(SourceFile:47) ~[?:?] {re:classloading}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:observerlib:coremodmethod,xf:fml:astralsorcery:sun_brightness_server,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:850) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:786) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_271] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.state.StateHolder.func_177229_b(SourceFile:95) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:ferritecore:Replace StateHolder::getValues in StateHolder::toString,pl:mixin:APP:ferritecore.fastmap.mixin.json:FastMapStateHolderMixin,pl:mixin:APP:ferritecore.nopropertymap.mixin.json:NoPropertyStateHolderMixin,pl:mixin:A}
	at com.ridanisaurus.emendatusenigmatica.blocks.OreRedstone.activate(OreRedstone.java:109) ~[emendatusenigmatica:1.1] {re:classloading,pl:runtimedistcleaner:A}
	at com.ridanisaurus.emendatusenigmatica.blocks.OreRedstone.func_176199_a(OreRedstone.java:91) ~[emendatusenigmatica:1.1] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.entity.Entity.func_213315_a(Entity.java:564) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:astralsorcery:add_custom_entity_collision,pl:mixin:APP:randompatches.mixins.json:EntityMixin,pl:mixin:APP:structure_gel.mixins.json:EntityMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.EntityAccess,pl:mixin:APP:quark.mixins.json:EntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.entity.item.minecart.AbstractMinecartEntity.func_180459_n(AbstractMinecartEntity.java:393) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:quark.mixins.json:AbstractMinecartEntityMixin,pl:mixin:APP:assets/botania/botania.mixins.json:MixinAbstractMinecartEntity,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.entity.item.minecart.AbstractMinecartEntity.func_70071_h_(AbstractMinecartEntity.java:317) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:quark.mixins.json:AbstractMinecartEntityMixin,pl:mixin:APP:assets/botania/botania.mixins.json:MixinAbstractMinecartEntity,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.entity.item.minecart.TNTMinecartEntity.func_70071_h_(SourceFile:47) ~[?:?] {re:classloading}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}

-- Entity being ticked --

Details:
	Entity Type: minecraft:tnt_minecart (net.minecraft.entity.item.minecart.TNTMinecartEntity)
	Entity ID: 3379026
	Entity Name: Minecart with TNT
	Entity's Exact location: 861.50, 9.00, 5362.50
	Entity's Block location: World: (861,9,5362), Chunk: (at 13,0,2 in 53,335; contains blocks 848,0,5360 to 863,255,5375), Region: (1,10; contains chunks 32,320 to 63,351, blocks 512,0,5120 to 1023,255,5631)
	Entity's Momentum: 0.00, -0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

Stacktrace:
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:observerlib:coremodmethod,xf:fml:astralsorcery:sun_brightness_server,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
</pre>
</p>
</details>

**Comment by NillerMedDild** [comment]
Updating to 0.3.7 or 0.3.8 fixes this :)

**Comment by r-mc2** [comment]
Ah, I see #882 now, thank you >_>
I really shoulda checked that crashlog, I ignored it last night due to thinking it was some interaction of the paraglider in the title of that issue that was the root cause.

Out of curiosity what ended up being the problem/solution to this? Based on comments in the other one it sounded like it was a race condition of sorts? Checking if a TNT cart should do something before the block that was being checked had generated?

Also is there anything special I should do before/after updating to v0.3.8? e.g. delete the region file/chunk to ensure clean gen?

**Comment by NillerMedDild** [comment]
Yeah I think it was something like that, not sure tbh :P Rid fixed it in Emendatus Enigmatica. Deleting the region file or chunk that was causing an issue would be a safe bet :)
