### ISSUE TITLE
modpack server refuses all connections

### ISSUE THREAD

**Issue by brachnar** [NillerMedDild/Enigmatica6#1367]
**Modpack version**
Enigmatica6Server-0.3.10

**Describe the bug**
I have been trying to set up a server for enigmatica6 within a docker container. I create the stack using portainer and it creates the container but it is in a constant state of unhealthy.  the container says this.
```
failed to ping localhost:25565 : could not connect to Minecraft server: dial tcp 127.0.0.1:25565: connect: connection refused
```

I also get the following error whenever i try and connect to the server from the minecraft client
```
io.netty.channel.AbstractChannel$AnnotatedConnectException: connection refused: no further information
```

If I leave the container to run for a bit it starts to spit out this error. 
```
[20:20:14] [main/INFO] [minecraft/SimpleReloadableResourceManager]: Reloading ResourceManager: KubeJS Virtual Data Pack [low priority], Default, ftb-essentials-1604.1.0.13.jar, justenoughbeacons-3.1-1.16.3.jar, mcw-windows-1.0.2-mc1.16.4.jar, bambooeverything-1.16.3-forge-1.0.0.jar, modnametooltip_1.16.2-1.15.0.jar, pitg-1.16.3-1.4.1.jar, BetterCaves-Forge-1.16.4-1.1.1.jar, ForgeEndertech-1.16.4-7.0.9.0-build.0032.jar, CTM-MC1.16.1-1.1.2.6.jar, YungsApi-1.16.4-Forge-3.jar, Powah-1.16.4-2.3.9.jar, rangedpumps-0.8.2.jar, Wither-Skeleton-Tweaks-1.16.4-5.3.0.jar, Shrink-1.16.4-1.0.7.jar, randompatches-2.2.0-forge.jar, Morpheus-1.16.4-4.2.68.jar, gunswithoutroses-1.16.4-1.0.6.jar, TMechworks-1.16.3+-2.2.3.jar, Paraglider-1.16.2-1.3.1.0.jar, supplementaries-0.9.22d.jar, emojiful-1.16.4-2.1.3.jar, refinedstorage-1.9.11.jar, structure_gel-1.16.4-1.7.5.jar, industrial-foregoing-1.16.5-3.2.8.4-f4f1a4d.jar, torchmaster-2.3.6.jar, TipTheScales-1.16.4-3.0.0.10.jar, BiomesOPlenty-1.16.4-13.0.0.430-universal.jar, ToolStats-1.16.4-5.0.1.jar, toughnessbar-6.1.jar, dungeons_plus-1.16.4-1.1.2.jar, mcw-trapdors-1.0.1-mc1.16.5.jar, masonry-1.16.3-0.3.6.jar, Botania-1.16.4-411.jar, SpawnerFix-1.16.2-1.0.0.2.jar, spark-forge.jar, curios-forge-1.16.4-4.0.3.5.jar, GameStages-1.16.4-6.0.4.jar, angelring-1.16.3-1.3.3.jar, ExtraStorage-1.16.4-1.3.1.jar, NaturesAura-33.4.jar, mcw-roofs-2.0.1-mc1.16.5-4.jar, observerlib-1.16.4-1.5.1.jar, ensorcelled-0.1a.jar, BetterBurning-1.16.5-6.0.2.jar, FastLeafDecay-v25.jar, CodeChickenLib-1.16.4-3.5.1.408-universal.jar, BetterMineshafts-Forge-1.16.4-2.0.1.jar, SimpleDiscordRichPresence-1.16.4-1.3.5.jar, forge-1.16.5-geckolib-3.0.4a.jar, DangerousStoneCutter-1.16.2-1.4.jar, QuarkOddities-1.16.3.jar, enigmatica-1.16.3-0.1.1.jar, mining-helmet-1.16.4-2.0.0.jar, vanillaexcavators-1.16.4-2.2.0.jar, Bountiful Baubles FORGE-1.16.3-0.0.2.jar, portable_stonecutter-1.16.4-1.3.2.jar, jei-1.16.4-7.6.1.65.jar, AttributeFix-1.16.5-10.0.1.jar, seals-1.16.3-2.0.0.jar, Mekanism-1.16.4-10.0.18.445.jar, caelus-forge-1.16.5-2.1.2.2.jar, invtweaks-1.16.4-1.0.1.jar, NaturesCompass-1.16.4-1.8.6.jar, [1.16.4]-additionalbars-1.6.0.jar, catjammies-1.0.0.jar, LibX-1.16.3-1.0.10.jar, AdHooks-1.16.4-6.1.2.0-build.0027.jar, curioofundying-forge-1.16.4-5.1.0.0.jar, FarmingForBlockheads_1.16.3-7.2.1.jar, pneumaticcraft-repressurized-1.16.5-2.9.4-126.jar, snowundertrees-1.16.4-v1.1.3.jar, pedestals-0.8r_hotfix_4.jar, additional_lights-1.16.4-2.1.3.jar, extradisks-1.16.4-1.5.0.jar, ImmersivePetroleum-1.16.4-3.1.0-2.jar, ironchest-1.16.4-11.2.10.jar, MythicBotany-1.16.3-1.2.0.jar, theoneprobe-1.16-3.0.7.jar, clockout-1.16.4-2.0.0.1.jar, MouseTweaks-2.13-mc1.16.2.jar, configswapper-1.1.jar, ImmersiveEngineering-1.16.4-4.1.2-129.jar, useful_railroads-1.16.4-1.4.6.35.jar, morevanillalib-1.16.4-1.3.9.jar, SaveYourPets-1.16.2-1.0.0.5.jar, EmendatusEnigmatica-1.16.4-1.1.5.jar, Mantle-1.16.5-1.6.79.jar, ftb-backups-2.1.1.6.jar, serverconfigupdater-1.3.jar, polymorph-forge-1.16.4-0.23.jar, JustEnoughProfessions-1.16.3-1.1.jar, AutoRegLib-1.6-47.jar, tamedsummon-1.0.0.jar, FastFurnace-1.16.4-4.4.0.jar, lootr-1.16.4-0.0.4.11.jar, connectedglass-1.0.6-mc1.16.4.jar, occultism-1.0.8.jar, byg-1.1.8.jar, extremeSoundMuffler-3.6_Forge-1.16.4.jar, CosmeticArmorReworked-1.16.5-v1.jar, EnderMail-1.16.4-1.2.0.jar, DefaultOptions_1.16.3-12.2.0.jar, tetra-1.16.4-3.5.3.jar, rsrequestify-1.16.3-2.0.1.jar, astralsorcery-1.16.4-1.13.9.jar, NetherPortalFix_1.16.3-7.2.1.jar, aiotbotania-1.16.4-1.7.0.jar, eidolon-0.2.7.jar, KleeSlabs_1.16.3-9.2.0.jar, rsgauges-1.16.4-1.2.8.jar, findme-1.16.3-2.1.0.0.jar, glassential-forge-1.16.4-1.1.5.jar, MoreMobGriefingOptions-1.16.5-1.0.0.jar, CookingForBlockheads_1.16.3-9.2.2.jar, Controlling-7.0.0.12.jar, Placebo-1.16.4-4.4.1.jar, dankstorage-3.14.jar, citadel-1.5.3.jar, alexsmobs-1.4.1.jar, mightyarchitect-mc1.16.3_v0.5.jar, Bookshelf-1.16.5-10.0.1.jar, DarkUtilities-1.16.5-8.0.1.jar, BotanyPots-1.16.5-7.0.2.jar, BotanyTrees-1.16.5-3.0.1.jar, Tips-1.16.4-3.0.2.jar, sophisticatedbackpacks-1.16.4-1.3.4.136.jar, u_team_core-1.16.4-3.1.17.192.jar, buildinggadgets-1.16.4-3.7.3.jar, forge-1.16.5-36.0.1-universal.jar, PassthroughSigns-1.16.4-2.3.7.jar, cofh_core-1.16.3-1.1.6.jar, thermal_foundation-1.16.3-1.1.6.jar, thermal_innovation-1.16.3-1.1.7.jar, thermal_locomotion-1.16.3-1.1.6.jar, plonk-1.16.5-9.0.7.jar, AppleSkin-mc1.16.2-forge-1.0.14.jar, Aquaculture-1.16.4-2.1.12.jar, mcw-doors-1.0.2-mc1.16.5.jar, MekanismGenerators-1.16.4-10.0.18.445.jar, FpsReducer-mc1.16.4-1.18.jar, XNetGases-1.16.4-2.2.3.jar, LostTrinkets-1.16.4-0.1.13.jar, restriction-1.16.4-0.0.3.jar, cobblegenrandomizer-1.16-5.1.2.jar, PrettyPipes-1.9.1.jar, chocolate-1.3.0-1.16.4.jar, mcw-bridges-1.0.5-mc1.16.5-4.jar, FarmersDelight-1.16.3-0.3.1.jar, useful_backpacks-1.16.4-1.11.6.87.jar, ResourcefulBees1.16.3-1.16.4-0.5.8b.jar, DustrialDecor-1.1.5.jar, Curious Armor Stands-1.16.3-2.0.2.jar, Ping-1.16.4-1.6.9.jar, valhelsia_structures-16.0.5.jar, Lollipop-1.16.4-3.2.4.jar, ftb-ranks-1604.1.1.10.jar, rare-ice-0.2.2.jar, simplylight-1.16.4-1.1.1.jar, simplefarming-1.16.4-1.3.5.jar, Patchouli-1.16.4-48.jar, ars_nouveau-1.16.4-1.11.2.jar, cakechomps-forge-1.16.4-5.0.0.2.jar, blockcarpentry-1.16-0.3.5a.jar, thermal_expansion-1.16.3-1.1.6.jar, DrawersTooltip-1.16.2-2.1.0.jar, elevatorid-1.16.5-1.7.12.jar, ftb-ultimine-1603.1.1.13.jar, buildersaddition-1.16.4-20210124a.jar, Runelic-1.16.4-6.0.4.jar, MekanismTools-1.16.4-10.0.18.445.jar, architectury-1.5.101-forge.jar, ftb-gui-library-1604.2.0.30-forge.jar, ftb-teams-1604.1.0.14-forge.jar, curiouselytra-forge-1.16.5-4.0.2.0.jar, cc-tweaked-1.16.4-1.95.2.jar, Storage4ComputerCraft-1.16.4-1.2.1.jar, AI-Improvements-1.16.2-0.3.0.jar, cherishedworlds-forge-1.16.4-5.1.0.0.jar, trashcans-1.0.6a-mc1.16.4.jar, The_Undergarden-1.16.5-0.4.5.jar, InventoryEssentials_1.16.3-2.3.0.jar, bwncr-1.16.4-3.9.16.jar, ServerTabInfo-1.16.4-1.3.3.jar, QuantumStorage-1.16.4-5.3.0.jar, BetterAdvancements-1.16.4-0.1.0.104.jar, rhino-1.7.13.10.jar, kubejs-1605.3.4.151-forge.jar, kubejs-thermal-1604.1.0.5.jar, kubejs-immersive-engineering-1604.1.0.12.jar, kubejs-mekanism-1604.1.1.6.jar, BotaniaAdditionsMC1.16.4-1.0.4.jar, BedBenefits-1.16.5-5.0.2.jar, TrashSlot_1.16.3-12.2.1.jar, craftingstation-4.1.1.jar, OldJavaWarning-1.16.4-6.0.1.jar, item-filters-1605.2.3.20-forge.jar, ftb-quests-1604.1.1.21.jar, ensorcellation-1.16.3-1.1.2.jar, create-mc1.16.3_v0.3e.jar, kubejs-create-1604.1.0.4.jar, Waystones_1.16.3-7.3.1.jar, Clumps-6.0.0.13.jar, mgui-1.16.4-3.1.3.jar, comforts-forge-1.16.4-4.0.1.0.jar, Artifacts-1.16.4-2.7.5.jar, framedcompactdrawers-1.16-2.2.0.jar, decorative_blocks-1.16.4-1.7.2.jar, DungeonCrawl-1.16.3-2.2.4.jar, demagnetize-forge-1.16.2-1.2.2.jar, TravelAnchors-2.1.jar, mcjtylib-1.16-5.0.15.jar, rftoolsbase-1.16-2.0.9.jar, xnet-1.16-3.0.11.jar, rftoolspower-1.16-3.0.8.jar, rftoolsbuilder-1.16-3.0.13.jar, rftoolsstorage-1.16-2.0.8.jar, rftoolscontrol-1.16-4.0.6.jar, mapperbase-1.16.4-2.3.0.0.jar, embellishcraft-1.16.4-3.3.0.0.jar, bedspreads-forge-1.16.4-5.1.0.1.jar, Interactio-1.16.4-3.1.1.jar, iChunUtil-1.16.3-10.0.0.jar, mininggadgets-1.7.1.jar, EnderStorage-1.16.4-2.7.1.166-universal.jar, AkashicTome-1.4-15.jar, ftb-chunks-1604.2.2.61.jar, campfiretorches-1.16.3-1.0.3.jar, BloodMagic-1.16.3-3.0.6-11.jar, tomeofblood-1.16.4-1.0.5.jar, kubejs-blood-magic-1604.1.0.4.jar, recipebuffers-2.1.jar, meetyourfight-1.16.4-1.1.0.jar, immersiveposts-1.16.3-3.0.0.jar, CraftingTweaks_1.16.3-12.2.0.jar, rftoolsutility-1.16-3.0.20.jar, EnchantmentDescriptions-1.16.4-6.0.3.jar, swingthroughgrass-1.16.4-1.5.3.jar, titanium-1.16.4-3.2.5.jar, CreativeCore_v2.0.10_mc1.16.4.jar, Undergarden-Tetra Patch-1.1.1.jar, archers_paradox-1.16.3-1.1.1.jar, towers_of_the_wild-1.16.4-2.0.1.jar, Quark-r2.4-298.jar, Apotheosis-1.16.3-4.4.1.jar, cookiecore-1.16.2-3.0.2-9389769.jar, magicfeather-1.16.2-3.1.0.jar, JAOPCA-1.16.4-3.4.0.3.jar, FastWorkbench-1.16.4-4.5.0.jar, StorageDrawers-1.16.3-8.2.2.jar, vanillahammers-1.16.4-2.2.0.jar, scaffoldingpower-1.16.3-1.2.1.jar, World Stripper-1.16.4-2.0.1.jar, Transport-1.16.4-3.4.1.jar, ferritecore-1.1.1.jar, engineersdecor-1.16.4-1.1.7.jar, solcarrot-1.16.3-1.9.9.jar, BackTools-1.16.3-10.0.0.jar, moredragoneggs-1.4.jar, modular-routers-1.16.4-7.3.1-50.jar, refinedstorageaddons-0.7.2.jar, overloadedarmorbar-5.1.0.jar, chiselsandbits-0.2.10-RELEASE.jar, Morph-o-Tool-1.4-26.jar, inmemory:jaopca, KubeJS Resource Pack [data], KubeJS Virtual Data Pack [high priority]

[20:21:17] [Worker-Main-13/ERROR] [minecraft/JsonReloadListener]: Couldn't parse data file buildersaddition:cabinet/cabinet_warped_quark from buildersaddition:recipes/cabinet/cabinet_warped_quark.json

com.google.gson.JsonParseException: com.google.gson.stream.MalformedJsonException: Unterminated array at line 25 column 2 path $.conditions[1]

	at net.minecraft.util.JSONUtils.func_188173_a(SourceFile:495) ~[?:?] {re:classloading}

	at net.minecraft.util.JSONUtils.func_193839_a(SourceFile:532) ~[?:?] {re:classloading}

	at net.minecraft.client.resources.JsonReloadListener.func_212854_a_(JsonReloadListener.java:48) ~[?:?] {re:computing_frames,re:mixin,re:classloading}

	at net.minecraft.client.resources.JsonReloadListener.func_212854_a_(JsonReloadListener.java:22) ~[?:?] {re:computing_frames,re:mixin,re:classloading}

	at net.minecraft.client.resources.ReloadListener.func_215270_b(SourceFile:11) ~[?:?] {re:computing_frames,re:mixin,re:classloading}

	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) [?:1.8.0_212] {}

	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582) [?:1.8.0_212] {}

	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_212] {}

	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_212] {}

	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_212] {}

	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_212] {}

Caused by: com.google.gson.stream.MalformedJsonException: Unterminated array at line 25 column 2 path $.conditions[1]

	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559) ~[server-1.16.5-20210115.111550-extra.jar:?] {}

	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:476) ~[server-1.16.5-20210115.111550-extra.jar:?] {}

	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:414) ~[server-1.16.5-20210115.111550-extra.jar:?] {}

	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:730) ~[server-1.16.5-20210115.111550-extra.jar:?] {}

	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:739) ~[server-1.16.5-20210115.111550-extra.jar:?] {}

	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:714) ~[server-1.16.5-20210115.111550-extra.jar:?] {}

	at com.google.gson.internal.bind.TypeAdapters$35$1.read(TypeAdapters.java:910) ~[server-1.16.5-20210115.111550-extra.jar:?] {}

	at net.minecraft.util.JSONUtils.func_188173_a(SourceFile:493) ~[?:?] {re:classloading}
      
	... 10 more
```

I have tried another modpack server to see if it is the docker container or the modpack and the other modpack worked first time. The docker code I am using is as follows:
```
version: '3.2'

services:
  mc:
    image: itzg/minecraft-server:java8
    volumes:
    - /docker/minecraft/modpacks:/modpacks:ro
    environment:
      EULA: "true"
      TYPE: CURSEFORGE
      CF_SERVER_MOD: /modpacks/Enigmatica6Server-0.3.10.zip
    ports:
      - 25565:25565
```

**Comment by NillerMedDild** [comment]
Why are you using 0.3.10? It's an alpha version, and outdated. Please try again with 0.3.13 :)

**Comment by NillerMedDild** [comment]
The latest log from the client would be helpful btw.

**Comment by brachnar** [comment]
i have upgraded to the 0.3.13 and am still getting the errors.  this is the error from the client when i try to connect to the server.

```[22Feb2021 17:42:02.046] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 512x256x0 minecraft:textures/atlas/particles.png-atlas
[22Feb2021 17:42:02.065] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[22Feb2021 17:42:02.127] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 256x256x0 minecraft:textures/atlas/mob_effects.png-atlas
[22Feb2021 17:42:02.415] [Render thread/INFO] [ambientsounds/]: Successfully loaded sound engine. 11 dimension(s) and 32 region(s)
[22Feb2021 17:42:48.171] [Render thread/INFO] [Astral Sorcery/]: Client cache cleared!
[22Feb2021 17:42:48.208] [Render thread/INFO] [net.minecraft.client.gui.screen.ConnectingScreen/]: Connecting to 192.168.0.9, 25565
[22Feb2021 17:42:59.225] [Server Connector #1/ERROR] [net.minecraft.client.gui.screen.ConnectingScreen/]: Couldn't connect to server
io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: NAS.lan/192.168.0.9:25565
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:1.8.0_241]
	at sun.nio.ch.SocketChannelImpl.finishConnect(Unknown Source) ~[?:1.8.0_241]
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:325) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:635) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:582) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:499) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:461) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at java.lang.Thread.run(Unknown Source) ~[?:1.8.0_241]
Caused by: java.net.ConnectException: Connection refused: no further information
	... 10 more
[22Feb2021 17:43:12.581] [Render thread/INFO] [Astral Sorcery/]: Client cache cleared!
[22Feb2021 17:43:12.591] [Render thread/INFO] [net.minecraft.client.gui.screen.ConnectingScreen/]: Connecting to 192.168.0.9, 25565
[22Feb2021 17:43:23.613] [Server Connector #2/ERROR] [net.minecraft.client.gui.screen.ConnectingScreen/]: Couldn't connect to server
io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: NAS.lan/192.168.0.9:25565
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:1.8.0_241]
	at sun.nio.ch.SocketChannelImpl.finishConnect(Unknown Source) ~[?:1.8.0_241]
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:325) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:635) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:582) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:499) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:461) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at java.lang.Thread.run(Unknown Source) ~[?:1.8.0_241]
Caused by: java.net.ConnectException: Connection refused: no further information
	... 10 more
[22Feb2021 17:43:35.471] [Render thread/INFO] [net.minecraft.client.Minecraft/]: Stopping!
[22Feb2021 17:43:35.479] [Render thread/INFO] [Astral Sorcery/]: Client cache cleared!
[22Feb2021 17:43:35.692] [DiscordRP Stop/INFO] [Simple Discord Rich Presence/]: Discord client closed.
```

**Comment by NillerMedDild** [comment]
Alright. What about server's latest.log?

**Comment by brachnar** [comment]
https://pastebin.com/NXpvSSky

**Comment by NillerMedDild** [comment]
That's hopefully not the entire server latest.log - It hasn't started in that one.

**Comment by NillerMedDild** [comment]
I'll set this up locally and see what I can break :P

**Comment by brachnar** [comment]
i wonder if it the docker container doesn't start enigmatica 6's server for some reason.  i will try anf go into the docker container and start it manually

**Comment by NillerMedDild** [comment]
I would imagine it's running out of RAM, 1GB isn't a lot.

**Comment by brachnar** [comment]
ah.  i think that the docker container sets ram at 1gb unless specified otherwise.  i shall rewrite the socker compose and see how it goes

**Comment by brachnar** [comment]
ok that fixed the servers unhealthy statues.  it is now running on 2.5GB of ram so i have set it to have a max of 6 for now.  but now it is crashing the client
here is the client logs
https://pastebin.com/H5hYRAwa

and here is the server log
https://pastebin.com/X2iN2Cd5

**Comment by NillerMedDild** [comment]
I see no crash in the client log?

**Comment by brachnar** [comment]
i think it is a issue with the server as it says on line 1994 of that log
```
[20:00:07] [Netty Epoll Server IO #11/ERROR] [minecraft/ArgumentTypes]: Could not serialize dev.maxneedssnacks.interactio.command.RegistryArgument@578ddbb3 (class dev.maxneedssnacks.interactio.command.RegistryArgument) - will not be sent to client!
```

amd then 2 lines down on 1996
```
[20:03:07] [Server thread/INFO] [minecraft/ServerPlayNetHandler]: brachnar lost connection: Timed out
```
could it be that the client got stuck waiting for the server which simple didn't send anything?

**Comment by NillerMedDild** [comment]
No, the first error is normal and is also displayed when succesfully connecting. I was able to make this setup work, albeit with a very long startup time. I suspect lack of RAM is the issue, possibly your total RAM amount - How much do you have?

My `docker-compose.yml` for reference:

```yml
version: "3.2"

services:
  minecraft:
    image: itzg/minecraft-server:java8
    volumes:
      #  Uses the modpacks folder in the same folder as the docker-compose.yml for the server files to install
      - ./modpacks:/modpacks:ro
      #  Uses the data folder in the same folder as the docker-compose.yml for config, mods, world etc
      # - ./data:/data
    environment:
      EULA: "true"
      TYPE: CURSEFORGE
      # The modpack zip you've downloaded from https://www.curseforge.com/minecraft/modpacks/enigmatica6/files
      CF_SERVER_MOD: /modpacks/Enigmatica6Server-0.3.13.zip
      # Default RAM allocation
      MEMORY: 5G
      OPS: NillerMedDild
    ports:
      - 25565:25565
    restart: unless-stopped
```

**Comment by brachnar** [comment]
I tried doing it again and this time it worked.  think my computer just decided that it was taking too long to respond

my docker file is the same minutes the line:
```
OPS: NillerMedDild
```

Thanks for the help

**Comment by NillerMedDild** [comment]
Sure thing, glad it works!
