### ISSUE TITLE
Crash on first launch of 0.4.1 server [Retry should fix it]

### ISSUE THREAD

**Issue by localzuk** [NillerMedDild/Enigmatica6#1444]
On a freshly downloaded server 0.4.1 server, running the setup results in a crash. 

Description: Exception in server tick loop

```
com.electronwill.nightconfig.core.io.WritingException: An I/O error occured
	at com.electronwill.nightconfig.core.io.ConfigWriter.write(ConfigWriter.java:90) ~[core-3.6.2.jar:?] {}
	at com.electronwill.nightconfig.core.file.WriteSyncFileConfig.save(WriteSyncFileConfig.java:61) ~[core-3.6.2.jar:?] {}
	at com.electronwill.nightconfig.core.file.AutosaveCommentedFileConfig.save(AutosaveCommentedFileConfig.java:80) ~[core-3.6.2.jar:?] {}
	at net.minecraftforge.fml.config.ModConfig.save(ModConfig.java:94) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.config.ConfigTracker.openConfig(ConfigTracker.java:107) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.config.ConfigTracker.lambda$loadConfigs$1(ConfigTracker.java:83) ~[forge:?] {re:classloading}
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_262] {}
	at java.util.Collections$SynchronizedCollection.forEach(Collections.java:2064) ~[?:1.8.0_262] {}
	at net.minecraftforge.fml.config.ConfigTracker.loadConfigs(ConfigTracker.java:83) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.server.ServerLifecycleHooks.handleServerAboutToStart(ServerLifecycleHooks.java:95) ~[forge:?] {re:classloading}
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:166) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:621) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262] {}
Caused by: java.nio.file.FileSystemException: .\world\serverconfig\occultism-server.toml: The process cannot access the file because it is being used by another process.
```

**Comment by NillerMedDild** [comment]
Thanks for the report - Does it keep happening? There's an ongoing issue with Forge and config reloading.

**Comment by localzuk** [comment]
Re-running the server-start.bat after the crash seems to have got past whatever the issue was, and the server loads OK.

**Comment by NillerMedDild** [comment]
Glad to hear it :)

**Comment by MizozPL** [comment]
I haven't experienced any crashes on first boot (clean install). But I'm starting the server from the command line with:
`jdk8u282-b08-jre\bin\java.exe -jar -Xmx4G -Xms4G -d64 -server -XX:+AggressiveOpts -XX:+UseConcMarkSweepGC -XX:+UnlockExperimentalVMOptions -XX:+UseParNewGC -XX:+ExplicitGCInvokesConcurrent -XX:+UseFastAccessorMethods -XX:+OptimizeStringConcat -XX:+UseAdaptiveGCBoundary forge-1.16.5-36.0.40.jar nogui`

**Comment by Shadowmanji** [comment]
playing on 0.4.1, just did the update from 0.4.0 and I'm getting that audio error. Running the server from a linux box

**Comment by Merlo17** [comment]
Audio error?

**Comment by Shadowmanji** [comment]
> ATAL] [minecraft/Main]: Failed to start the minecraft server
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
Ding has class loading errors
§7java.lang.NoClassDefFoundError: net/minecraft/client/audio/ISound
]
at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:184) ~[forge:?] {re:classloading}
at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:44) ~[forge:?] {re:classloading}
at net.minecraft.server.Main.main(Main.java:95) ~[?:?] {re:classloading}
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_282] {}
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_282] {}
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_282] {}
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_282] {}
at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[forge-1.16.5-36.0.40.jar:36.0] {}
at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}
at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}
at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [forge-1.16.5-36.0.40.jar:?] {}
at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [forge-1.16.5-36.0.40.jar:?] {}
at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [forge-1.16.5-36.0.40.jar:?] {}

**Comment by Merlo17** [comment]
I'm not sure how this is related to this issue but ding is a client side only mod, so it shouldn't be on your server

**Comment by Shadowmanji** [comment]
alright

**Comment by NillerMedDild** [comment]
Use the server files for servers :) they don't have client mods that cause issues.

**Comment by Merlo17** [comment]
Resolved on discord. Niller they were wondering why there's no remove client mods.sh script for linux, since they were not able to run that. Some other scripts seem to not have linux versions at first glance. Am I missing something?

**Comment by NillerMedDild** [comment]
Because Linux users can simply run the .ps1 scripts directly :)
