### ISSUE TITLE
[0.4.8] Crash during world creation

### ISSUE THREAD

**Issue by hron84** [NillerMedDild/Enigmatica6#2043]
**Modpack version** 0.4.8

**Describe the bug**
After starting a world in a freshly installed instance with the very default settings (Terraforged worldgen, nothing changed), world creation just hangs and a crash being logged 

**Logs**

```
java.lang.NullPointerException
        at net.minecraft.util.ResourceLocation.func_195823_b(ResourceLocation.java:60)
        at net.minecraft.util.ResourceLocation.<init>(ResourceLocation.java:38)
        at tictim.paraglider.ModCfg.parseWindSources(ModCfg.java:123)
        at tictim.paraglider.ModCfg.onLoad(ModCfg.java:111)
        at net.minecraftforge.eventbus.ASMEventHandler_98_ModCfg_onLoad_ModConfigEvent.invoke(.dynamic)
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
        at net.minecraftforge.fml.ModContainer.lambda$dispatchConfigEvent$7(ModContainer.java:152)
        at java.util.Optional.ifPresent(Optional.java:159)
        at net.minecraftforge.fml.ModContainer.dispatchConfigEvent(ModContainer.java:152)
        at net.minecraftforge.fml.config.ModConfig.fireEvent(ModConfig.java:90)
        at net.minecraftforge.fml.config.ConfigTracker.openConfig(ConfigTracker.java:106)
        at net.minecraftforge.fml.config.ConfigTracker.lambda$loadConfigs$1(ConfigTracker.java:83)
        at java.lang.Iterable.forEach(Iterable.java:75)
        at java.util.Collections$SynchronizedCollection.forEach(Collections.java:2064)
        at net.minecraftforge.fml.config.ConfigTracker.loadConfigs(ConfigTracker.java:83)
        at net.minecraftforge.fml.server.ServerLifecycleHooks.handleServerAboutToStart(ServerLifecycleHooks.java:95)
        at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:59)
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:621)
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232)
        at java.lang.Thread.run(Thread.java:748)

[24Apr2021 11:22:54.469] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
java.lang.NullPointerException: null
        at net.minecraft.util.ResourceLocation.func_195823_b(ResourceLocation.java:60) ~[?:?]
        at net.minecraft.util.ResourceLocation.<init>(ResourceLocation.java:38) ~[?:?]
        at tictim.paraglider.ModCfg.parseWindSources(ModCfg.java:123) ~[paraglider:1.3.1.0]
        at tictim.paraglider.ModCfg.onLoad(ModCfg.java:111) ~[paraglider:1.3.1.0]
        at net.minecraftforge.eventbus.ASMEventHandler_98_ModCfg_onLoad_ModConfigEvent.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
        at net.minecraftforge.fml.ModContainer.lambda$dispatchConfigEvent$7(ModContainer.java:152) ~[forge:?]
        at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_242]
        at net.minecraftforge.fml.ModContainer.dispatchConfigEvent(ModContainer.java:152) ~[forge:?]
        at net.minecraftforge.fml.config.ModConfig.fireEvent(ModConfig.java:90) ~[forge:?]
        at net.minecraftforge.fml.config.ConfigTracker.openConfig(ConfigTracker.java:106) ~[forge:?]
        at net.minecraftforge.fml.config.ConfigTracker.lambda$loadConfigs$1(ConfigTracker.java:83) ~[forge:?]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_242]
        at java.util.Collections$SynchronizedCollection.forEach(Collections.java:2064) ~[?:1.8.0_242]
        at net.minecraftforge.fml.config.ConfigTracker.loadConfigs(ConfigTracker.java:83) ~[forge:?]
        at net.minecraftforge.fml.server.ServerLifecycleHooks.handleServerAboutToStart(ServerLifecycleHooks.java:95) ~[forge:?]
        at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:59) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:621) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
```
[latest.log](https://github.com/NillerMedDild/Enigmatica6/files/6369322/latest.log)

**Comment by Darkere** [comment]
looks like an invalid value in one of your configs. Try reinstalling or recopying the configs.
