### ISSUE TITLE
Problems installing Server on Linux

### ISSUE THREAD

**Issue by Frostcup** [NillerMedDild/Enigmatica6#2092]
[22:20:47] [INFO] Attempting to download installer from http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.16.5-36.1.13/forge-1.16.5-36.1.13-installer.jar
[22:21:18] [ERROR] Problem while installing Loader

java.net.SocketTimeoutException: connect timed out
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:607)
        at okhttp3.internal.platform.Platform.connectSocket(Platform.java:129)
        at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:240)
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:160)
        at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)
        at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
        at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
        at okhttp3.RealCall.execute(RealCall.java:77)
        at atm.bloodworkxgaming.serverstarter.InternetManager.downloadToFile(InternetManager.kt:51)
        at atm.bloodworkxgaming.serverstarter.LoaderManager.installLoader(LoaderManager.kt:115)
        at atm.bloodworkxgaming.serverstarter.ServerStarter.startLoading(ServerStarter.kt:167)
        at atm.bloodworkxgaming.serverstarter.ServerStarterKt.main(ServerStarter.kt:202)
[22:21:18] [INFO] Starting to installing Additional Files
[22:21:18] [INFO] Starting to copy local files.
[22:21:18] [INFO] Starting Loader, output incoming
Error: Unable to access jarfile /opt/minecraft/forge-NONE-NONE.jar
[22:21:18] [INFO] Server has been stopped, it has started 1 times in 60min
[22:21:18] [INFO] Restarting server in 10 seconds, press ctrl+c to stop

**Comment by NillerMedDild** [comment]
Thanks for the report. Could you please delete the `serverstart.lock` file and run the script again? Hopefully this was just a fluke.

**Comment by Frostcup** [comment]
no change, same error

**Comment by NillerMedDild** [comment]
What about if you download that version of the forge installer manually and put it in the folder?

**Comment by Frostcup** [comment]
in the main minecraft folder?

**Comment by NillerMedDild** [comment]
Yep

**Comment by Frostcup** [comment]
already tryed that, same error.
Cause of the failed download it trys to start forge-NONE-NONE.jar

Should i rename my manual download to that?

**Comment by Seceroth** [comment]
Sounds similar to the issue I had, but didn't to report on GitHub, just Discord.

![Knipsel (2)](https://user-images.githubusercontent.com/20866237/116933636-5435b100-ac53-11eb-9025-208d53bf0646.PNG)

The serverstarter.jar does not recognize manually downloaded forge jars.

**Comment by NillerMedDild** [comment]
I can't reproduce the issue sadly :/ which OS are you on?

**Comment by Seceroth** [comment]
If you're asking me, windows 7.

**Comment by NillerMedDild** [comment]
In that case I wasn't asking you :P Seceroth you used the bat right?
@Frostcup which flavor of Linux are you using?

**Comment by Seceroth** [comment]
Yes, using start-server.bat. It also failes to download serverstarter-2.0.1.jar, but it does work until the forge issue after manually downloading serverstarter-2.0.1.jar.

**Comment by NillerMedDild** [comment]
Could you try the .sh just for kicks? :P

**Comment by Frostcup** [comment]
@NillerMedDild 
uname -a
Linux h2892536.stratoserver.net 4.15.0 #1 SMP Tue Jun 9 12:58:54 MSK 2020 x86_64 x86_64 x86_64 GNU/Linux

i am trying to find the real version behind it, its a root server

**Comment by NillerMedDild** [comment]
I think you should run the serverstart locally and upload the files :/ not sure what else to do really. I don't see why it shouldn't work on Ubuntu though.

**Comment by Seceroth** [comment]
As expected the .sh has the same error as it's the serverstarter.jar causing the issue. I've already installed the server manually, but for the next modpack version it'd be nice if this went more smoothly.

**Comment by NillerMedDild** [comment]
Would you mind trying to install ATM6's server files? I'd like to see if it's the fork of ServerStarter I'm using or what :)
https://www.curseforge.com/minecraft/modpacks/all-the-mods-6/files/3287544

**Comment by Frostcup** [comment]
same behavior 
[terminal.txt](https://github.com/NillerMedDild/Enigmatica6/files/6418090/terminal.txt)

**Comment by Seceroth** [comment]
Making me work hard for it huh, Niller. :P
Same error. This is what shows up before manually downloading the serverstarter, btw:

![Knipsel](https://user-images.githubusercontent.com/20866237/116940197-1d649880-ac5d-11eb-995c-d78e53aa1a3e.PNG)

**Comment by NillerMedDild** [comment]
Alright, thanks 👍 I'll see what I can do from here. May I ping either of you in case I need to validate a fix?

**Comment by Frostcup** [comment]
sure :)

**Comment by NillerMedDild** [comment]
How's your internet connection? The errors indicate that it's unstable (that's what Google told me anyway :P)

**Comment by Frostcup** [comment]
should be stable, its a hosted root server

**Comment by NillerMedDild** [comment]
I don't know what a root server is, but alright 👍

**Comment by Frostcup** [comment]
basicly a full rented vm, not just a service (root rights on the vm)

**Comment by NillerMedDild** [comment]
Ahh okay! Nice.

**Comment by Seceroth** [comment]
I would assume my connection is fine. The modpack zip downloads fine from media.forgecdn.net and all the mods from curse as well. Just the download from files.minecraftforge.net is not working.
The 'okhttp3' version included in serverstarter seems to be over 3 years old, though that may not be an issue.
From what I've found for serverstarter-2.0.1.jar not downloading, it may not work for me because "/dynamic" is not a valid argument for the Windows 7 version of BitsAdmin.

**Comment by Frostcup** [comment]
got it working for me :P 
Basicly for whatever reason, the server could not reach the forge installer download path.
I downloaded it and uploaded it to my google drive, then i changed the download path in the server-setup-config.yaml 
to the file in my google drive.

**Comment by NillerMedDild** [comment]
Nice, gj 😄
