### ISSUE TITLE
FTBChunks - Server worlds crashing client after upgrading to 0.5.9

### ISSUE THREAD

**Issue by scoobz-x** [NillerMedDild/Enigmatica6#2922]
**Modpack version**
0.5.9

FTBChunks latest release causing server to crash client when opening FTBchunks ingame on an upgraded world from 0.5.6
Easy to replicate.

create world in 0.5.6 on server and claim some chunks. upgrade to 0.5.9. open ftbchunks. client crash not server

Maybe related to this below. if so might be worth putting in changelog to start fresh world.

![Untitled](https://user-images.githubusercontent.com/81186098/128626615-2c1661b8-cf21-468d-8391-17d935053fdc.png)

**Comment by Darkere** [comment]
That message is for people upgrading from previous release versions. We've moved on from those versions in 0.5.0. As such any ftb crashes are normal crashes and should be reported to them.

**Comment by scoobz-x** [comment]
Ok not related then. I will look further. recovered server back to 0.5.6 will re-upgrade and check logs. Only suspecting FTBchunks as client crash happens when clicking the FTBchunks button in JEI

**Comment by NillerMedDild** [comment]
Please provide the crash report :)

**Comment by Scironex** [comment]
If I may, I'm having the same issue, and I have a crash report I can provide. Two, as a matter of fact, but I'll just post the most recent one for now.
[crash-2021-08-08_18.41.52-client.txt](https://github.com/NillerMedDild/Enigmatica6/files/6951566/crash-2021-08-08_18.41.52-client.txt)

**Comment by ArMoReDfUrY** [comment]
it's maybe possible that this is caused by FPS Reducer.
recent patch to address a multi click event bug  released a few hours ago.
from patch notes - v1.23
- Fixed the issue where the immediate recovering from very low FPS sometimes doesn't work.
- Fixed the issue that multiple click action occurs when recovering from very low FPS with a mouse click.
- Fixed the issue that sound volume and FPS recover intermittently with mouse scroll action in inactive.

not 100% but i do see the click event mentioned in the crash report.

**Comment by Darkere** [comment]
How would multiple clicks make FTB unable to find the dimension they are in? Even if, FTBChunks should handle that.

**Comment by ArMoReDfUrY** [comment]
im just going off Scironex posted crash report.

it calls - Description: mouseClicked event handler

at line 29 - 	
at bre2el.fpsreducer.handler.glfw.InputEventHandler$MouseButtonEventHandler.invoke(InputEventHandler.java:99) ~[?:mc1.16.5-1.20] {re:classloading}

i just figured it may be related.
as i said, not 100% sure.

**Comment by Darkere** [comment]
Ah. That call is likely in every mouseclick.

The actual problem appears on line 57

```Caused by: java.lang.NullPointerException
	at dev.ftb.mods.ftbchunks.client.map.MapDimension.getCurrent(MapDimension.java:34)```

**Comment by ArMoReDfUrY** [comment]
i see... i must have skimmed over that a little too quick.

**Comment by EvilEpicPanda** [comment]
> Ah. That call is likely in every mouseclick.
> 
> The actual problem appears on line 57
> 
> ```
> Caused by: java.lang.NullPointerException
> 	at dev.ftb.mods.ftbchunks.client.map.MapDimension.getCurrent(MapDimension.java:34)
> ```

I've been disconnecting from my server due to a `java.lang.NullPointerException` so this seems promising.

**Comment by Darkere** [comment]
`java.lang.NullPointerException`

Is the most common Java Error. This means absolutely nothing.
