### ISSUE TITLE
requestify crafting emitter crashing on fluid mode

### ISSUE THREAD

**Issue by Quezler** [NillerMedDild/Enigmatica6#2948]
**Modpack version**

0.5.9

**Describe the bug**

placed the new crafting emitter down to check it out and switched it from item to liquid mode, causing the client to instantly give the transparent grey overlay & crash, i'm assuming its because we have no fluids on the network yet? 🤔

(bricked world, server crash log & latest.log available on request if deemed necessary to debug this further) 

**Logs**

```
java.lang.NullPointerException
	at com.buuz135.refinedstoragerequestify.proxy.block.network.NetworkNodeCraftingEmitter.update(NetworkNodeCraftingEmitter.java:85)
	at com.refinedmods.refinedstorage.apiimpl.network.NetworkListener.onWorldTick(NetworkListener.java:25)
	at net.minecraftforge.eventbus.ASMEventHandler_1753_NetworkListener_onWorldTick_WorldTickEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPostWorldTick(BasicEventHooks.java:100)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:857)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787)
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642)
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

**Screenshots**

failed to take one.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by Darkere** [comment]
Depending on where the block saves it's data you should be able to modify it back to item mode. Best guess is it's stored on the tile. But it is possible that it is stored in the refindestorage_nodes.dat instead.

**Comment by Quezler** [comment]
> Depending on where the block saves it's data you should be able to modify it back to item mode. Best guess is it's stored on the tile. But it is possible that it is stored in the refindestorage_nodes.dat instead.

luckly after the [integrated dynamic incident](https://discord.com/channels/195234321836146688/726178356143456287/872034672023052368) that broke my previous world i had set the backup interval from 2h to 15m, so i didn't mind rolling back this time around 😇

**Comment by Quezler** [comment]
@NillerMedDild https://github.com/Buuz135/RS-Requestify/commit/1e713e311927e5acc25fab7f64b0fa5f99758c58
