### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by Nickos04** [NillerMedDild/Enigmatica6#3031]
### Modpack Version

0.5.10

### Describe your issue

Server is on hosting. Server is crashing randomly while exploring.

[18Aug2021 20:42:59.942] [Server console handler/ERROR] [net.minecraft.server.dedicated.DedicatedServer/]: Caught previously unhandled exception :
java.io.IOError: java.io.IOException: Error executing 'stty -a': stty: 'standardowe wejście': Błąd wejścia/wyjścia
	at org.jline.terminal.impl.AbstractPosixTerminal.setAttributes(AbstractPosixTerminal.java:54) ~[jline-3.12.1.jar:?]
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:650) ~[jline-3.12.1.jar:?]
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:418) ~[jline-3.12.1.jar:?]
	at net.minecraftforge.server.console.TerminalHandler.handleCommands(TerminalHandler.java:60) ~[forge:?]
	at net.minecraft.server.dedicated.DedicatedServer$1.run(DedicatedServer.java:84) ~[?:?]
Caused by: java.io.IOException: Error executing 'stty -a': stty: 'standardowe wejście': Błąd wejścia/wyjścia
	at org.jline.utils.ExecHelper.exec(ExecHelper.java:42) ~[jline-3.12.1.jar:?]
	at org.jline.terminal.impl.ExecPty.doGetConfig(ExecPty.java:175) ~[jline-3.12.1.jar:?]
	at org.jline.terminal.impl.ExecPty.getAttr(ExecPty.java:87) ~[jline-3.12.1.jar:?]
	at org.jline.terminal.impl.ExecPty.doSetAttr(ExecPty.java:93) ~[jline-3.12.1.jar:?]
	at org.jline.terminal.impl.AbstractPty.setAttr(AbstractPty.java:29) ~[jline-3.12.1.jar:?]
	at org.jline.terminal.impl.AbstractPosixTerminal.setAttributes(AbstractPosixTerminal.java:52) ~[jline-3.12.1.jar:?]
	... 4 more

[debug-1.log](https://github.com/NillerMedDild/Enigmatica6/files/7009500/debug-1.log)
[2021-08-18-1.log](https://github.com/NillerMedDild/Enigmatica6/files/7009501/2021-08-18-1.log)

### Crash Report

https://github.com/NillerMedDild/Enigmatica6/files/7009500/debug-1.log

### Latest Log

https://github.com/NillerMedDild/Enigmatica6/files/7009501/2021-08-18-1.log

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by RaVenInTheDark** [comment]
It doesn't seem like an issue with the pack at all. A standard server shutdown occurred before this (aka not a crash, the server was told to stop by something) and then the server had an issue processing what was passed to console (by your host) afterwards. What exactly is `stty`?

On another note, you attached a debug log, not a crash report.

**Comment by RaVenInTheDark** [comment]
> It doesn't seem like an issue with the pack at all. A standard server shutdown occurred before this (aka not a crash, the server was told to stop by something) and then the server had an issue processing what was passed to console (by your host) afterwards. What exactly is `stty`?
> 
> On another note, you attached a debug log, not a crash report. 

I'm fairly confident in saying that your host is 100% to blame. What host is it?

**Comment by Nickos04** [comment]
Polish specific hosting - liveserver.pl - i don't really know what is stty ("On Unix-like operating systems, the stty command changes and prints terminal line settings.").
I can write to guys from my hosting to check issue with them but i don't know if they'd be willing to help in this case.
