### ISSUE TITLE
Console error spam holding an Akashic tome'd Lexica Botania in hand.

### ISSUE THREAD

**Issue by ThePB** [NillerMedDild/Enigmatica6#3228]
### Modpack Version

0.5.11

### Describe your issue

As title.

Simply holding an AKT with a LB selected in hand is enough to cause an incredibly fast spam of:

`[19:16:14] [Render thread/WARN] [botania/]: Failed to render lexicon
java.lang.NullPointerException: null
	at vazkii.botania.client.core.handler.RenderLexicon.doRender(RenderLexicon.java:160) ~[botania:1.16.5-419] {re:classloading}
	at vazkii.botania.client.core.handler.RenderLexicon.renderFirstPersonItem(RenderLexicon.java:105) ~[botania:1.16.5-419] {re:classloading}
	at vazkii.botania.client.core.handler.RenderLexicon.renderHand(RenderLexicon.java:82) ~[botania:1.16.5-419] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.client.ForgeHooksClient.renderSpecificFirstPersonHand(ForgeHooksClient.java:162) ~[forge:?] {re:classloading,re:mixin}
	at net.minecraft.client.renderer.FirstPersonRenderer.func_228396_a_(FirstPersonRenderer.java:243) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:forge:bows.1,xf:fml:forge:crossbows.0,xf:fml:forge:crossbows.1,xf:fml:forge:filled_map.0,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorFirstPersonRenderer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_228381_a_(GameRenderer.java:369) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:astralsorcery:reach_set_client_renderer,pl:mixin:APP:flywheel.mixins.json:StoreProjectionMatrixMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:614) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:astralsorcery:reach_set_client_renderer,pl:mixin:APP:flywheel.mixins.json:StoreProjectionMatrixMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:425) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:astralsorcery:reach_set_client_renderer,pl:mixin:APP:flywheel.mixins.json:StoreProjectionMatrixMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:betterendforge.mixins.json:MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:abnormals_core.mixins.json:client.MinecraftMixin,pl:mixin:APP:kubejs-common.mixins.json:MinecraftMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:betterendforge.mixins.json:MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:abnormals_core.mixins.json:client.MinecraftMixin,pl:mixin:APP:kubejs-common.mixins.json:MinecraftMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[minecraft-1.16.5-client.jar:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_301] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_301] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_301] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_301] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.2.2-launcher.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_301] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_301] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_301] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_301] {}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:52) [ForgeWrapper-1.5.1.jar:1.5.1] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_301] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_301] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_301] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_301] {}
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?] {}
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?] {}`

in the console. As the first line states, there has to be some sort of rendering error for the cover of the LB, since there's no text at all where there should be (if not for a split second upon selection).

Happens with both versions of the book, does not happen with a non-AKT version of the books, even if it is the SAME book taken out from the tome.

### Crash Report

-

### Latest Log

-

### Have you modified the modpack?

Yes

### User Modifications

As other issues: nothing that i think might impact, but... changed configs for Waystones/JM compat, reduced the number of backups... biggest thing i've changed tetra spears to allow for sword enchants, but that's really it.

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
Thanks for the report. Could you please provide your full latest.log? :)

**Comment by ThePB** [comment]
I know i should have prepared that one too... will do. But it's going to be the same as the one in the other thread just with a ton of what i quoted added for good measure :D

**Comment by ThePB** [comment]
Just FMI for next time, better make another post or edit the last one when it is just a small time gap?

[latest2.log](https://github.com/NillerMedDild/Enigmatica6/files/7150240/latest2.log)
(It is the latest.log, just renamed it since i've kept the other one too.)

Started at 22.24 with a non-AKT Lexica, then inserted it in the AKT at 22.25, then i am a goldfish and i don't remember what i did exactly (if extracted it or simply swapped item), then finally thrown it out of the AKT and taken the single book alone in hand before disconnecting.

**Comment by NillerMedDild** [comment]
> Just FMI for next time, better make another post or edit the last one when it is just a small time gap?

Separate issues for separate bugs is preferred, like you've done :)

**Comment by ThePB** [comment]
I meant updating an already existing "comment" with the log in this thread over leaving another comment (sorry, used the wrong terminology lead to confusion).

Thanks for the help!

**Comment by NillerMedDild** [comment]
Ahh I see - I prefer another comment, because I get notified of all comments :)
