### ISSUE TITLE
[Windows11] ServerStarter -  Failed to connect to maven.minecraftforge.net

### ISSUE THREAD

**Issue by Shadowgar** [NillerMedDild/Enigmatica6#3336]
### Modpack Version

0.5.11 0.5.13 0.5.14

### Describe your issue.

When clicking on start-server.bat, eventually the script errors with 

` [00:52:18] [INFO] Attempting to download installer from https://maven.minecraftforge.net/net/minecraftforge/forge/1.16.5-36.2.4/forge-1.16.5-36.2.4-installer.jar
[00:52:39] [ERROR] Problem while installing Loader
 
java.net.ConnectException: Failed to connect to maven.minecraftforge.net/2607:5300:203:65a5:0:0:0:0:443
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:242)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:160)
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
	at okhttp3.RealCall.execute(RealCall.java:77)
	at atm.bloodworkxgaming.serverstarter.InternetManager.downloadToFile(InternetManager.kt:51)
	at atm.bloodworkxgaming.serverstarter.LoaderManager.installLoader(LoaderManager.kt:115)
	at atm.bloodworkxgaming.serverstarter.ServerStarter.startLoading(ServerStarter.kt:167)
	at atm.bloodworkxgaming.serverstarter.ServerStarterKt.main(ServerStarter.kt:202)
Caused by: java.net.ConnectException: Connection timed out: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	at okhttp3.internal.platform.Platform.connectSocket(Platform.java:129)
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:240)
	... 21 more `

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server
[serverstarter.log](https://github.com/NillerMedDild/Enigmatica6/files/7249012/serverstarter.log)

**Comment by NillerMedDild** [comment]
Thanks for the report. I am unable to reproduce this issue, which operating system are you using?

**Comment by Shadowgar** [comment]
> Thanks for the report. I am unable to reproduce this issue, which operating system are you using?

Version	10.0.22000 Build 22000


The only way I was able to bypass this issue was to manually download and install the forge-1.16.5-36.2.4-installer.jar into the main folder after the serverstarter failed and then put in my own serverstart.bat like below.

`java -Xms6G -Xmx6G -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true -Dfml.readTimeout=90 -Dfml.queryResult=confirm -jar forge-1.16.5-36.2.4.jar nogui
pause`

**Comment by NillerMedDild** [comment]
> Version 10.0.22000 Build 22000

Of what? Windows 10? Home/pro?

**Comment by Shadowgar** [comment]
> > Version 10.0.22000 Build 22000
> 
> Of what? Windows 10? Home/pro?

This would be windows 10 home upgraded to 11.

**Comment by NillerMedDild** [comment]
Yay, more Windows 11 issues :P I can't do much there tbh, I don't know what they broke in the upgrade to 11, but apparently several things.

**Comment by NillerMedDild** [comment]
Darkere informed me that Windows 11 is now officially released, so we need to investigate this some more ^^'
