### ISSUE TITLE
Roadrunner duplicate entity issue causing crashes

### ISSUE THREAD

**Issue by TheAdamizer** [NillerMedDild/Enigmatica6#3577]
### Modpack Version

0.5.16

### Describe your issue.

This [issue](https://github.com/MaxNeedsSnacks/roadrunner/issues/12) on roadrunner causing crashes in new SP worlds.
Ran for about 30 minutes before running into this and being unable to load back into the world.

Red herring error on launcher will likely get people stuck trying to figure out how to fix this.

Removing roadrunner fixed the problem, and also had no noticeable decrease in performance after being gone.

Recommendation: Keep roadrunner solely to the server pack, if at all.

Stack Trace:

```
[26Oct2021 08:56:36.511] [Server thread/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID d66f87d3-9a2d-49f7-9e7b-0ecff5118778
[26Oct2021 08:56:36.514] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
net.minecraft.crash.ReportedException: Ticking block entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:855) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.IllegalStateException: Adding Entity listener a second time: me.jellysquid.mods.lithium.common.entity.tracker.nearby.NearbyEntityListenerMulti@46aaf567 with sublisteners: [me.jellysquid.mods.lithium.common.entity.tracker.nearby.NearbyEntityTracker@19b1cdd5 for entity class: net.mehvahdjukaar.dummmmmmy.entity.TargetDummyEntity, in rangeSq: 144.0, around entity: ResourcefulBee['Forest Bee'/137586, l='ServerLevel[New World]', x=-1186.50, y=98.27, z=-47.69] with NBT: {NoGravity:1b,Brain:{memories:{}},HurtByTimestamp:0,ForgeData:{"naturesaura:time_alive":18400},FlowerPos:{X:-1040,Y:67,Z:56},HasStung:0b,Attributes:[{Base:0.08d,Name:"forge:entity_gravity"},{Base:0.0d,Name:"minecraft:generic.knockback_resistance"},{Base:48.0d,Modifiers:[{Amount:0.05668093122532465d,Operation:1,UUID:[I;-676509792,-1871822630,-1432876499,1221453782],Name:"Random spawn bonus"}],Name:"minecraft:generic.follow_range"},{Base:0.30000001192092896d,Name:"minecraft:generic.movement_speed"}],Invulnerable:0b,FallFlying:0b,ForcedAge:0,PortalCooldown:0,AbsorptionAmount:0.0f,BeeType:"forest",FallDistance:0.0f,InLove:0,CanUpdate:1b,DeathTime:0s,BoundingBox:[-1186.762499988079d,98.2749999910593d,-47.95d,-1186.237500011921d,98.7250000089407d,-47.42500002384186d],ForgeCaps:{"structure_gel:gel_entity":{portal:"structure_gel:empty"},"mekanism:radiation":{radiation:1.0E-7d},"citadel:extended_entity_data_citadel":{},"pneumaticcraft:hacking":{},"shrink:shrunk":{width:0.525f,defaulteyeheight:0.22500001f,scale:1.0f,fixed:0b,isshrunk:0b,height:0.45000002f},"eidolon:knowledge":{signs:[],facts:[]}},HandDropChances:[0.085f,0.085f],CannotEnterHiveTicks:0,PersistenceRequired:0b,FeedCount:0,UUID:[I;-1374293381,-1822471274,-1983328376,1117990458],mutationCount:0,Age:0,TicksSincePollination:0,AngerTime:0,Motion:[-0.005346024976752203d,0.13701108740998724d,0.06248455455878735d],Health:10.0f,HasNectar:0b,LeftHanded:0b,Air:300s,OnGround:0b,CitadelData:{},Rotation:[262.6374f,0.0f],HandItems:[{},{}],ArmorDropChances:[0.085f,0.085f,0.085f,0.085f],Pos:[-1186.5d,98.2749999910593d,-47.68750001192093d],Fire:-1s,ArmorItems:[{},{},{},{}],CropsGrownSincePollination:0,CanPickUpLoot:0b,HurtTime:0s,HivePos:{X:-1187,Y:98,Z:-49}}]
 wants to listen at: SectionPos{x=-75, y=6, z=-3} with cube radius: 1
 but was already listening at chunk sections: SectionPos{x=-76, y=5, z=-5}, SectionPos{x=-76, y=5, z=-4}, SectionPos{x=-76, y=5, z=-3}, SectionPos{x=-76, y=6, z=-5}, SectionPos{x=-76, y=6, z=-4}, SectionPos{x=-76, y=6, z=-3}, SectionPos{x=-76, y=7, z=-5}, SectionPos{x=-76, y=7, z=-4}, SectionPos{x=-76, y=7, z=-3}, SectionPos{x=-75, y=5, z=-5}, SectionPos{x=-75, y=5, z=-4}, SectionPos{x=-75, y=5, z=-3}, SectionPos{x=-75, y=6, z=-5}, SectionPos{x=-75, y=6, z=-4}, SectionPos{x=-75, y=6, z=-3}, SectionPos{x=-75, y=7, z=-5}, SectionPos{x=-75, y=7, z=-4}, SectionPos{x=-75, y=7, z=-3}, SectionPos{x=-74, y=5, z=-5}, SectionPos{x=-74, y=5, z=-4}, SectionPos{x=-74, y=5, z=-3}, SectionPos{x=-74, y=6, z=-5}, SectionPos{x=-74, y=6, z=-4}, SectionPos{x=-74, y=6, z=-3}, SectionPos{x=-74, y=7, z=-5}, SectionPos{x=-74, y=7, z=-4}, SectionPos{x=-74, y=7, z=-3}
	at me.jellysquid.mods.lithium.common.entity.tracker.EntityTrackerEngine.addListener(EntityTrackerEngine.java:85) ~[roadrunner:1.3.0]
	at me.jellysquid.mods.lithium.common.entity.tracker.EntityTrackerEngine.onEntityAdded(EntityTrackerEngine.java:42) ~[roadrunner:1.3.0]
	at net.minecraft.world.chunk.Chunk.handler$bcp000$onEntityAdded(Chunk.java:1422) ~[?:?]
	at net.minecraft.world.chunk.Chunk.func_76612_a(Chunk.java:330) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_72838_d(ServerWorld.java:818) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_217376_c(ServerWorld.java:754) ~[?:?]
	at net.minecraft.tileentity.BeehiveTileEntity.func_235651_a_(SourceFile:246) ~[?:?]
	at net.minecraft.tileentity.BeehiveTileEntity.func_226976_y_(SourceFile:275) ~[?:?]
	at net.minecraft.tileentity.BeehiveTileEntity.func_73660_a(SourceFile:289) ~[?:?]
	at net.minecraft.world.World.func_217391_K(MixinWorldRedstone.java:491) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:371) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?]
	... 5 more
```

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by shinji257** [comment]
I would like to report that this happens server side as well.  We have been hitting this rather randomly on our server and it crash stalls when the incident occurs.

**Comment by novaexe** [comment]
https://github.com/MaxNeedsSnacks/roadrunner/issues/12 contains the temp solution to this issue by the dev himself towards the bottom
