### ISSUE TITLE
"Colliding entity with block" exception (applied energistics)

### ISSUE THREAD

**Issue by Quezler** [NillerMedDild/Enigmatica6#361]
**Modpack version**
`Enigmatica6-0.2.17`

**Issue**
dropping items (charged certus quartz / nether quartz / redstone) with the formation plane causes the server to crash:
(not sure if it as an issue of applied energistics or the combinations of versions & mods in this pack, dumping it here)

**Logs**
(sounds as though the item entities that are dropped or the resulting fluix crystal items collide with a block somehow?)

```
[09:46:37] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
net.minecraft.crash.ReportedException: Colliding entity with block
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:856) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:286) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:788) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:643) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:230) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_272] {}
Caused by: java.lang.NullPointerException
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770) ~[server-1.16.1-20200625.160719-extra.jar:?] {}
        at appeng.util.Platform.poweredInsert(Platform.java:823) ~[?:8.0.0-beta.2] {re:classloading,pl:runtimedistcleaner:A}
        at appeng.util.Platform.poweredInsert(Platform.java:816) ~[?:8.0.0-beta.2] {re:classloading,pl:runtimedistcleaner:A}
        at appeng.parts.automation.AnnihilationPlanePart.storeItemStack(AnnihilationPlanePart.java:243) ~[?:8.0.0-beta.2] {re:classloading}
        at appeng.parts.automation.AnnihilationPlanePart.storeEntityItem(AnnihilationPlanePart.java:223) ~[?:8.0.0-beta.2] {re:classloading}
        at appeng.parts.automation.AnnihilationPlanePart.onEntityCollision(AnnihilationPlanePart.java:199) ~[?:8.0.0-beta.2] {re:classloading}
        at appeng.parts.CableBusContainer.onEntityCollision(CableBusContainer.java:648) ~[?:8.0.0-beta.2] {re:classloading}
        at appeng.block.networking.CableBusBlock.func_196262_a(CableBusBlock.java:118) ~[?:8.0.0-beta.2] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.block.AbstractBlock$AbstractBlockState.func_196950_a(AbstractBlock.java:621) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:kubejs.mixins.json:AbstractBlockStateMixin,pl:mixin:APP:assets/passablefoliage/passablefoliage.mixins.json:MixinBlockState,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.entity.Entity.func_145775_I(Entity.java:827) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:quark:generic-update-hook,xf:fml:immersiveengineering:IE wire damage,xf:fml:quark:redirect-fire-resistance,xf:fml:randompatches:RandomPatches Entity Transformer,pl:runtimedistcleaner:A}
        at net.minecraft.entity.Entity.func_213315_a(Entity.java:579) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:quark:generic-update-hook,xf:fml:immersiveengineering:IE wire damage,xf:fml:quark:redirect-fire-resistance,xf:fml:randompatches:RandomPatches Entity Transformer,pl:runtimedistcleaner:A}
        at net.minecraft.entity.item.ItemEntity.func_70071_h_(ItemEntity.java:113) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:interactio.mixins.json:ItemEntityMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorItemEntity,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:604) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:endergetic:patch_server_world,xf:fml:quark:change-sleeping-player-count,xf:fml:quark:add-rave-hook,xf:fml:immersiveengineering:IE block update callback,pl:runtimedistcleaner:A}
        at net.minecraft.world.World.func_217390_a(World.java:596) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:397) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:endergetic:patch_server_world,xf:fml:quark:change-sleeping-player-count,xf:fml:quark:add-rave-hook,xf:fml:immersiveengineering:IE block update callback,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:852) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        ... 5 more
```

**Comment by Quezler** [comment]
some extra info on the setup:

- both the formation and the annihilation plane have a cable facade
- storage bus under the interface block has a fluix crystal filter
- formation pane is set to drop blocks as items (or it won't dump items at all)
- originally the formation pane was directly on top of the water block instead of the side of the air block above (debugged wether or not that was the issue)

![2020-11-07_10 55 30](https://user-images.githubusercontent.com/3179271/98438086-da7b9b00-20e7-11eb-84ce-99266786181c.png)
