### ISSUE TITLE
Builder crashes server if a mechanical pipe is ontop/below it.

### ISSUE THREAD

**Issue by Volensq** [NillerMedDild/Enigmatica6#477]
Version 0.3.0

[WARNING] This will crash the server/ local game every time trying to join  afterwards. So do it on a blank world if testing
Builder when having a Basic Mechanical Pipe above it and turning a builder on, Will cause a instant server crash/ singleplayer and multiplayer.
The card in builder was a liquid placer

Last bit of logs before crash
[03:46:58] [Server thread/INFO]: [Volensque: Gave 1 [Basic Mechanical Pipe] to Volensque]
[03:46:58] [Render thread/INFO]: [CHAT] Gave 1 [Basic Mechanical Pipe] to Volensque
[03:47:03] [Server thread/FATAL]: Preparing crash report with UUID 99d48840-0e0d-4d4b-be3b-5eb9b1789c11
[03:47:03] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.crash.ReportedException: Ticking block entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:854) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:786) ~[?:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:118) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641) [?:?]
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) [?:?]
	at net.minecraft.server.MinecraftServer$$Lambda$24740/1097928921.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:203) ~[?:1.8.0_51]
	at java.util.Optional.<init>(Optional.java:96) ~[?:1.8.0_51]
	at java.util.Optional.of(Optional.java:108) ~[?:1.8.0_51]
	at net.minecraftforge.common.util.LazyOptional.map(LazyOptional.java:206) ~[?:?]
	at mcjty.rftoolsbuilder.modules.builder.blocks.BuilderTileEntity.consumeLiquid(BuilderTileEntity.java:1630) ~[?:1.16-3.0.10]
	at mcjty.rftoolsbuilder.modules.builder.blocks.BuilderTileEntity.consumeLiquid(BuilderTileEntity.java:1615) ~[?:1.16-3.0.10]
	at mcjty.rftoolsbuilder.modules.builder.blocks.BuilderTileEntity.placeLiquidBlock(BuilderTileEntity.java:1274) ~[?:1.16-3.0.10]
	at mcjty.rftoolsbuilder.modules.builder.items.ShapeCardType$$Lambda$12747/105438514.handleSingleBlock(Unknown Source) ~[?:?]
	at mcjty.rftoolsbuilder.modules.builder.items.ShapeCardType.handleSingleBlock(ShapeCardType.java:200) ~[?:1.16-3.0.10]
	at mcjty.rftoolsbuilder.modules.builder.blocks.BuilderTileEntity.handleSingleBlock(BuilderTileEntity.java:1060) ~[?:1.16-3.0.10]
	at mcjty.rftoolsbuilder.modules.builder.blocks.BuilderTileEntity.handleBlockShaped(BuilderTileEntity.java:1001) ~[?:1.16-3.0.10]
	at mcjty.rftoolsbuilder.modules.builder.blocks.BuilderTileEntity.checkStateServerShaped(BuilderTileEntity.java:737) ~[?:1.16-3.0.10]
	at mcjty.rftoolsbuilder.modules.builder.blocks.BuilderTileEntity.checkStateServer(BuilderTileEntity.java:775) ~[?:1.16-3.0.10]
	at mcjty.rftoolsbuilder.modules.builder.blocks.BuilderTileEntity.func_73660_a(BuilderTileEntity.java:749) ~[?:1.16-3.0.10]
	at net.minecraft.world.World.func_217391_K(World.java:491) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:371) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:850) ~[?:?]
	... 6 more

**Comment by MuteTiefling** [comment]
![2020-12-04_09 48 00](https://user-images.githubusercontent.com/9543430/101177532-eb033080-3615-11eb-936c-6eb764ae6c3a.png)

Tried to reproduce in the current Dev instance and cannot. Would you mind please uploading the full Latest and Crash logs? 

This may already be fixed, however. In the meantime, does it work for you if you've got a tank there instead of a pipe?

**Comment by Volensq** [comment]
It was just a pipe. no water in it.

**Comment by MuteTiefling** [comment]
That also appears to be fine in my dev instance. I'll try later in the current release, but complete logs are going to be needed. 

![2020-12-04_11 31 27](https://user-images.githubusercontent.com/9543430/101188900-548a3b80-3624-11eb-9931-4e2519b0c578.png)

**Comment by NillerMedDild** [comment]
This was fixed in a recent update :)
https://www.curseforge.com/minecraft/mc-mods/rftools-builder/files/3120453
