### ISSUE TITLE
[Server Crash][Ars Noveau] Using cut spell against ghast's fireball causes ClassCastException

### ISSUE THREAD

**Issue by lunchza** [NillerMedDild/Enigmatica6#819]
**Modpack version**
0.3.5

**Issue**
Server crash when using Ars Noveau ranged projectile spell in fight against Ghast
The spell I was using  using is the following sequence:
[Projectile][Harm][Amplify][Cut][Amplify]

**Logs**
https://pastebin.com/vD2WCh0G

**Stack Trace**
`java.lang.ClassCastException: net.minecraft.entity.projectile.FireballEntity cannot be cast to net.minecraft.entity.LivingEntity
	at com.hollingsworth.arsnouveau.api.spell.AbstractEffect.dealDamage(AbstractEffect.java:93) ~[ars_nouveau:1.10.6] {re:classloading}
	at com.hollingsworth.arsnouveau.common.spell.effect.EffectCut.onResolveEntity(EffectCut.java:48) ~[ars_nouveau:1.10.6] {re:classloading}
	at com.hollingsworth.arsnouveau.api.spell.AbstractEffect.onResolve(AbstractEffect.java:48) ~[ars_nouveau:1.10.6] {re:classloading}
	at com.hollingsworth.arsnouveau.api.spell.SpellResolver.resolveEffects(SpellResolver.java:137) ~[ars_nouveau:1.10.6] {re:classloading}
	at com.hollingsworth.arsnouveau.api.spell.SpellResolver.onResolveEffect(SpellResolver.java:126) ~[ars_nouveau:1.10.6] {re:classloading}
	at com.hollingsworth.arsnouveau.common.entity.EntityProjectileSpell.func_70227_a(EntityProjectileSpell.java:212) ~[ars_nouveau:1.10.6] {re:classloading}
	at com.hollingsworth.arsnouveau.common.entity.EntityProjectileSpell.func_70071_h_(EntityProjectileSpell.java:101) ~[ars_nouveau:1.10.6] {re:classloading}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:observerlib:coremodmethod,xf:fml:astralsorcery:sun_brightness_server,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:850) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:786) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_271] {}`

**Comment by lunchza** [comment]
Edit: I can reliably reproduce this by timing the harm spell as the ghast fires, almost as if I was going to reflect his fireball back. The whole server crashes and users get disconnected

**Comment by NillerMedDild** [comment]
Thanks for the report, and finding the specific cause, that'll be very useful for the mod dev :D
